using DevExpress.XtraBars;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace QLVT
{
    public partial class frmNhanvien : DevExpress.XtraEditors.XtraForm
    {
        private Int32 ViTri = 0;
        public frmNhanvien()
        {
            InitializeComponent();

            WindowState = FormWindowState.Maximized;
            dateTimeNV.Format = DateTimePickerFormat.Custom;
            dateTimeNV.CustomFormat = "dd-MM-yyyy";
            
            
            // This line of code is generated by Data Source Configuration Wizard

        }


        private void HienThi()
        {
            txtDC.DataBindings.Clear();
            txtDC.DataBindings.Add("text", gcNV.DataSource , "DIACHI");
            txtHo.DataBindings.Clear();
            txtHo.DataBindings.Add("text", gcNV.DataSource, "HO");
            txtTen.DataBindings.Clear();
            txtTen.DataBindings.Add("text", gcNV.DataSource, "TEN");
            txtLuong.DataBindings.Clear();
            txtLuong.DataBindings.Add("text", gcNV.DataSource, "LUONG");
            txtMaNV.DataBindings.Clear();
            txtMaNV.DataBindings.Add("text", gcNV.DataSource, "MANV");
            txtMaCN.DataBindings.Clear();
            txtMaCN.DataBindings.Add("text", gcNV.DataSource, "MACN");
            dateTimeNV.DataBindings.Clear();
            dateTimeNV.DataBindings.Add("text", gcNV.DataSource, "NGAYSINH");
            
            
           

        }
        
        private void barButtonItem4_ItemClick(object sender, ItemClickEventArgs e)
        {

        }

        private void nhanVienBindingNavigatorSaveItem_Click(object sender, EventArgs e)
        {
            this.Validate();
            this.bdsNV.EndEdit();
            this.tableAdapterManager.UpdateAll(this.DS);

        }
        
        private void frmNhanvien_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'qLVT_DATHANGDataSet.NhanVien' table. You can move, or remove it, as needed.
            
            this.nhanVienTableAdapter.Connection.ConnectionString = Program.constr;
            // TODO: This line of code loads data into the 'qLVT_DATHANGDataSet.NhanVien' table. You can move, or remove it, as needed.
            this.nhanVienTableAdapter.Fill(this.DS.NhanVien);
          
            HienThi();
            grTTNV.Enabled = false;
            
            



        }

        private void gcNV_Click(object sender, EventArgs e)
        {

        }

        private void nhanVienBindingNavigatorSaveItem_Click_1(object sender, EventArgs e)
        {
            this.Validate();
            this.bdsNV.EndEdit();
            this.tableAdapterManager.UpdateAll(this.DS);

        }

        private void label6_Click(object sender, EventArgs e)
        {

        }

        private void gcNV_Click_1(object sender, EventArgs e)
        {
           
        }

        private void grTTNV_Paint(object sender, PaintEventArgs e)
        {

        }

        private void gcNV_Click_2(object sender, EventArgs e)
        {
            
        }

        private void dateTimeNV_ValueChanged(object sender, EventArgs e)
        {
            
        }

        private void barButtonItem8_ItemClick(object sender, ItemClickEventArgs e)
        {

        }

        private void barButtonItem3_ItemClick(object sender, ItemClickEventArgs e)
        {

        }

        private void barButtonItem10_ItemClick(object sender, ItemClickEventArgs e)
        {

        }
    }
}